Fix update-vendor issue and update all vendor folder to match with go.mod (#892)
* add kube::util::list_staging_repos

* fix hack/update-vendor.sh shellcheck failures

* fix hack/pin-dependency.sh shellcheck failures

* fix hack/verify-no-vendor-cycles.sh shellcheck failures

* document KUBE_ROOT in util.sh

* fix hack/update-vendor.sh array expansion

* Fix for build failure - viper now uses ConfigFileNotFoundError

Change-Id: I51c4fe26239c4a7bf750e0a6a66b452d9138832f

* update caddy vendor dependency to v1.0.3
kubernetes commit 9657240197974bab19e3661580eb34287b309aa7
remove github.com/mholt/caddy/caddyfile deps and change to github.com/caddyserver/caddy/caddyfile
hack/pin-dependency.sh github.com/caddyserver/caddy v1.0.3
hack/update-vendor.sh

* hack/pin-dependency.sh github.com/client9/misspell v0.3.4
hack/pin-dependency.sh github.com/coreos/go-semver v0.3.0
hack/pin-dependency.sh github.com/cpuguy83/go-md2man v1.0.10
hack/pin-dependency.sh github.com/cyphar/filepath-securejoin v0.2.2
hack/pin-dependency.sh k8s.io/klog v1.0.0
hack/pin-dependency.sh gotest.tools v2.2.0+incompatible
hack/pin-dependency.sh gotest.tools/gotestsum v0.3.5

* Drop github.com/coreos/etcd from all go.mod,go.sum. this already replaced by go.etcd.io/etcd
Remove etcd237/221 folder from third party
hack/pin-dependency.sh go.etcd.io/etcd v0.5.0-alpha.5.0.20200224211402-c65a9e2dd1fd
hack/update-vendor.sh

* Disable apiextensions-apiserver integration testing to fix “go: k8s.io/component-helpers@v0.0.0: unknown revision v0.0.0, go: k8s.io/mount-utils@v0.0.0: unknown revision v0.0.0, go: k8s.io/controller-manager@v0.0.0: unknown revision v0.0.0” when update-vendor.sh

* Drop Azure/go-autorest from pkg/controller

* drop dependency github.com/Azure/go-autorest v11.1.2+incompatible
hack/pin-dependency.sh github.com/Azure/go-autorest/autorest v0.9.0
hack/update-vendor.sh

* remove k8s.io/kubernetes/pkg/util/metrics import from apiserverconfigmanager.go

* fix cyclic dependency issue

* run hack/update-vendor.sh to update vendor folder

* Update Azure imports to v35.0.0 to fix azure-sdk-for-go build error
update to azure-sdk-for-go/services/compute/mgmt/2019-07-01
update to azure-sdk-for-go/services/storage/mgmt/2019-04-01
update to azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01
update to azure-sdk-for-go/services/network/mgmt/2019-06-01
hack/pin-dependency.sh github.com/Azure/azure-sdk-for-go v35.0.0+incompatible
hack/update-vendor.sh

* Fix the public IP getting issues for VMSS nodes

* fix: use Create for attach/detach disk

fix: revert typo

* fix azure-sdk-for-go build error

* Add/delete load balancer backendPoodID in VMSS.

* provider/azure: Fix load balancer distribution constants

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

* fix build error

* use vmss instance view expansion: kubernetes commit: 4fbdb08f98946be4a1277f59a32ab92b74670abe

* fix build error: azure_backoff.go:575:39: undefined: strings, azure_client.go:1037:29: not enough arguments in call to az.client.Get, azure_client.go:1386:34: not enough arguments in call to az.client.ListKeys
make quick-release

* fix make release error: pkg/cloudfabric-controller/controllerframework/controller_framework_utils.go:62:28: constant 9223372036854775807 overflows int

* fix make release error:
pkg/kubelet/dockershim/network/cni/cni_windows.go:47:36: not enough arguments in call to plugin.addToNetwork

Co-authored-by: Benjamin Elder <bentheelder@google.com>
Co-authored-by: Davanum Srinivas <davanum@gmail.com>
Co-authored-by: Ubuntu <ubuntu@ip-172-31-26-146.us-east-2.compute.internal>
Co-authored-by: Pengfei Ni <peni@microsoft.com>
Co-authored-by: andyzhangx <xiazhang@microsoft.com>
Co-authored-by: t-qini <t-qini@microsoft.com>
Co-authored-by: Stephen Augustus <saugustus@vmware.com>