upgrade Golang to 1.13.9 (#921)
* Switch to json test output

* Only output json format from tests when building junit reports

* opt out of module mode for builds

* e2e: fix full path support when reading viper config file

Something changed in Viper such that it now returns the
ConfigFileNotFound error when the config file is not found, for
example when it is specified including the .yaml or .json suffix.
When the code was originally was written, it returned "Unsupported
Config Type".

Found when adding a unit test for this code (separate commit because
it depends on the flag changes).

* e2e: avoid mandatory command line flags

Tests should never directly add to the global command line, because
some users of the tests might not want them there. For example,
options might only get set directly from a config file.

To achieve that, e2e/framework/config, e2e/framework/viperconfig, and
e2e/framework/test_context.go avoid using the global flag set and
instead expect to be told by the caller which flag set to use. Tests
that called flag directly either get updated or obsolete flags get
removed.

The exception is framework.HandleFlags, which as before directly
implements global command line handling.

This is a breaking change for test suites which do not use that
function (and only those): they now need to ensure that they copy
individual flags from tests. Because the RegisterCommonFlags prototype
has changed, test suite authors will notice due to the resulting
compilation errors.

* update Bazel

* remove github.com/kardianos/osext kubernetes#80142
hack/update-vendor.sh

* Move e2e_node flag copy into TestMain

As of go1.13, test flags like test.timeout are registered lazily.
This means they are not available in package init() methods:

> Testing flags are now registered in the new Init function,
> which is invoked by the generated main function for the test.
> As a result, testing flags are now only registered when running
> a test binary, and packages that call flag.Parse during package
> initialization may cause tests to fail.

This moves the copy of CLI flags into TestMain, just prior to parse.

* Fixup integration tests for TLS1.3

* Fix hack/pin-dependency.sh for go1.13

* Update build to go1.13.4 from kubernetes PR ##82809

* remove  jteeuwen/go-bindata because it is replaced by go-bindata/go-bindata

* hack/pin-dependency.sh github.com/heketi/heketi v9.0.1-0.20190917153846-c2e2a4ab7ab9+incompatible
hack/lint-dependencies.sh
hack/update-vendor.sh

* make update

* Fix ordering settings in verify bazel

In coreutils LC_ALL=C is required to make sorting stable across
platoforms and locales.

$ echo "a-c\nabc" | LANG=C LC_ALL=C sort
a-c
abc

$ echo "a-c\nabc" | LANG=C sort
abc
a-c

* Enable update-bazel.sh outside of GOPATH

* bump dependencies to support go1.13
        hack/pin-dependency.sh github.com/go-openapi/jsonpointer v0.19.5
        hack/pin-dependency.sh golang.org/x/crypto v0.0.0-20200220183623-bac4c82f6975
        hack/pin-dependency.sh golang.org/x/lint v0.0.0-20190409202823-959b441ac422
        hack/pin-dependency.sh golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
        hack/pin-dependency.sh golang.org/x/tools v0.0.0-20190920225731-5eefd052ad72
        hack/pin-dependency.sh golang.org/x/net v0.0.0-20201008223702-a5fa9d4b7c91
        hack/pin-dependency.sh golang.org/x/time v0.0.0-20191024005414-555d28b269f0
        hack/pin-dependency.sh golang.org/x/sys v0.0.0-20200622214017-ed371f2e16b4
        hack/pin-dependency.sh github.com/go-openapi/swag v0.19.5
        hack/pin-dependency.sh github.com/gregjones/httpcache v0.0.0-20180305231024-9cad4c3443a7
        hack/pin-dependency.sh github.com/mailru/easyjson v0.0.0-20190626092158-b2ccc519800e
        hack/pin-dependency.sh github.com/mattn/go-isatty v0.0.9
        hack/pin-dependency.sh github.com/pkg/errors v0.9.1
        hack/pin-dependency.sh github.com/spf13/pflag v1.0.5
        hack/pin-dependency.sh gopkg.in/inf.v0 v0.9.1
        hack/pin-dependency.sh github.com/heketi/heketi v9.0.1-0.20190917153846-c2e2a4ab7ab9+incompatible

* run hack/update-vendor.sh

* make update

* Add benchmarks for serializing PodList

* Update custom-serialization code to go backward

* Fix pkg-names script that doesn't select files properly

* Updating protobuf (v1.3.1)
hack/pin-dependency.sh github.com/gogo/protobuf v1.3.1
hack/lint-dependencies.sh
hack/update-vendor.sh

* make update

* updating dependency google.golang.org/grpc, github.com/prometheus/client_model, google.golang.org/genproto
hack/pin-dependency.sh google.golang.org/grpc v1.26.0
go mod edit -replace google.golang.org/genproto=google.golang.org/genproto@v0.0.0-20190819201941-24fa4b261c55
hack/pin-dependency.sh github.com/prometheus/client_model v0.2.0
hack/lint-dependencies.sh
hack/update-vendor.sh

* update github.com/golang/protobuf to v1.3.2
hack/pin-dependency.sh github.com/golang/protobuf v1.3.2
hack/lint-dependencies.sh
hack/update-vendor.sh

* update golang.org/x/crypto
hack/pin-dependency.sh golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
hack/lint-dependencies.sh
hack/update-vendor.sh

* fix bazel-test failure: TestRoundTripAndNewConnection
Use bigger keys for RSA-PSS, default for TLS 1.3 (Golang 1.13 requirement) kubernetes # #80734

* Update go version in go.mod to 1.13

* update vendor dependencies

    hack/pin-dependency.sh github.com/vishvananda/netlink v1.0.0
    hack/pin-dependency.sh github.com/docker/libnetwork v0.8.0-dev.2.0.20190624125649-f0e46a78ea34
    hack/pin-dependency.sh github.com/go-openapi/analysis v0.19.2
    hack/pin-dependency.sh github.com/BurntSushi/toml v0.3.1
    hack/pin-dependency.sh github.com/google/uuid v1.1.1
    hack/pin-dependency.sh github.com/gorilla/websocket v1.4.0
    hack/pin-dependency.sh github.com/hashicorp/hcl v1.0.0
    hack/pin-dependency.sh gopkg.in/natefinch/lumberjack.v2 v2.0.0
    hack/pin-dependency.sh github.com/kr/text v0.1.0
    hack/pin-dependency.sh github.com/seccomp/libseccomp-golang v0.9.1
hack/lint-dependencies.sh

* run hack/update-vendor.sh

* automatically set clinkopts

* supress libseccomp pkg-config errors

* automatically tag tests in test/integration/* as integration

* update vendor dependencies

    hack/pin-dependency.sh github.com/PuerkitoBio/purell v1.1.1
    hack/pin-dependency.sh github.com/asaskevich/govalidator v0.0.0-20190424111038-f61b66f89f4a
    hack/pin-dependency.sh github.com/kr/pty v1.1.5
    hack/pin-dependency.sh github.com/stretchr/objx v0.2.0
    hack/pin-dependency.sh github.com/sirupsen/logrus v1.4.2
hack/lint-dependencies.sh
hack/update-vendor.sh

* Build sample-apiserver image using go 1.13
Update wardle e2e image from kubernetes PR #84735

* Update to Golang 1.13.9 kubernetes #89400

* build: Enable kube-cross image-building on K8s Infra kubernetes #88562
kube-cross makefile add REGISTRY kubernete4s #79911

* build: Remove kube-cross image building from kubernetes # 89400
kube-cross image building has moved to k/release/images/build/cross.

* build/dependencies: Remove bazel WORKSPACE go_version check

When supplying the go_download_sdk instead of updating rules_go, the
go_version is removed, so we shouldn't check for it anymore in
hack/verify-external-dependencies-version.sh.

Without this, pull-kubernetes-verify jobs will fail.

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

* fix workspace go_register_toolchains() for 1.13.9

* pkg/util/workqueue/prometheus: fix double registration

Currently, if workqueue metrics are registered twice, these metrics will be ignored. This fixes it.

* pkg/util/workqueue: delete deprecated metrics

This deletes deprecated metrics and simplifies registration.

* Code cleanup for for probe/http

Two small code cleanup changes for `probe/http`.

- Tests name the `followNonLocalRedirects` variable before passing to
`New`, so its clear what the boolean flag in the construct impacts.
- Change import name from `httprobe` to `httpprobe` when used by
`pkg/kubelet/prober/prober.go`. Establishes consistency with other uses
in the repo.

* fixes for tests to pass with FIPS compiler

* use P256 ECDSA key since P224 is not supported
* regen test certs to be 2048bits

* make update

* Updating github.com/go-openapi dependencies
hack/pin-dependency.sh github.com/go-openapi/analysis v0.19.5
hack/pin-dependency.sh github.com/go-openapi/loads v0.19.4
hack/pin-dependency.sh github.com/go-openapi/spec v0.19.3
hack/pin-dependency.sh github.com/go-openapi/strfmt v0.19.3
hack/pin-dependency.sh github.com/go-openapi/validate v0.19.5
go mod edit -replace github.com/go-openapi/errors=github.com/go-openapi/errors@v0.19.2
go mod edit -replace github.com/go-openapi/runtime=github.com/go-openapi/runtime@0.19.4
go mod edit -replace github.com/go-openapi/jsonreference=github.com/go-openapi/jsonreference@v0.19.3
hack/pin-dependency.sh
hack/update-vendor.sh

* Update vendored dependencies to released version
go mod edit -replace gopkg.in/check.v1=gopkg.in/check.v1@v1.0.0-20180628173108-788fd7840127
hack/pin-dependency.sh github.com/coreos/go-semver v0.3.0
hack/pin-dependency.sh github.com/emicklei/go-restful v2.9.5+incompatible
hack/pin-dependency.sh github.com/evanphx/json-patch v4.9.0+incompatible
hack/pin-dependency.sh github.com/fatih/camelcase v1.0.0
hack/pin-dependency.sh github.com/kr/pretty v0.2.0
hack/pin-dependency.sh github.com/magiconair/properties v1.8.1
hack/pin-dependency.sh github.com/mattn/go-shellwords v1.0.5
hack/pin-dependency.sh github.com/onsi/ginkgo v1.11.0
hack/pin-dependency.sh github.com/onsi/gomega v1.7.0
hack/pin-dependency.sh github.com/stretchr/testify v1.4.0
hack/pin-dependency.sh gopkg.in/square/go-jose.v2 v2.3.1
hack/pin-dependency.sh gopkg.in/yaml.v2 v2.2.8
hack/pin-dependency.sh github.com/mistifyio/go-zfs v2.1.1+incompatible
hack/pin-dependency.sh github.com/mitchellh/go-wordwrap v1.0.0
hack/pin-dependency.sh github.com/mvdan/xurls v1.1.0
hack/pin-dependency.sh github.com/opencontainers/go-digest v1.0.0
hack/pin-dependency.sh github.com/opencontainers/image-spec v1.0.1
hack/pin-dependency.sh github.com/opencontainers/selinux v1.3.1-0.20190929122143-5215b1806f52
hack/pin-dependency.sh github.com/robfig/cron v1.1.0
hack/pin-dependency.sh github.com/spf13/afero v1.2.2
hack/pin-dependency.sh github.com/spf13/cobra v0.0.5
hack/pin-dependency.sh github.com/spf13/viper v1.3.2
hack/pin-dependency.sh github.com/spf13/jwalterweatherman v1.1.0
go mod edit -replace github.com/spf13/cast=github.com/spf13/cast@v1.3.0
hack/pin-dependency.sh github.com/miekg/dns v1.1.26

* run hack/update-vendor.sh
hack/pin-dependency.sh

* apiextensions: remove hacks around nullable

* make update

* Bump golang.org/x/tools version for staticcheck compat
hack/pin-dependency.sh golang.org/x/tools v0.0.0-20190920225731-5eefd052ad72
hack/pin-dependency.sh honnef.co/go/tools v0.0.1-2019.2.2
go mod edit -replace github.com/google/renameio=github.com/google/renameio@v0.1.0
go mod edit -replace github.com/rogpeppe/go-internal=github.com/rogpeppe/go-internal@v1.3.0
go mod edit -replace golang.org/x/mod=golang.org/x/mod@v0.0.0-20190513183733-4bf6d317e70e
go mod edit -replace gopkg.in/errgo.v2=gopkg.in/errgo.v2@v2.1.0
hack/lint-dependencies.sh
hack/update-vendor.sh

* Add static analysis verify script

* make update

* revert gopkg.in/square/go-jose.v2 to v2.2.2 to fix build error:
cannot use jwt.NumericDate(1514764800) (type jwt.NumericDate) as type *jwt.NumericDate in field value

* update containernetworking/cni to v0.7.1
hack/pin-dependency.sh github.com/containernetworking/cni v0.7.1
hack/lint-dependencies.sh
hack/update-vendor.sh

* move to libcni 0.7.0

Previous commit "Use ip address from CNI output" introduces
ability to run pod which can havn't eth0. But also it
add problem: after kubelet restart, if we have already started
pod w/o eth0, kubelet can't find proper interface (it's
normal for vhostuser type of cni plugin when eth0 doesn't exist)
and kubelet restarts "broken" pod.
Fix of this issue requeres new feature of libcni - caching
results.

Looks like new libcni requires cniVersion in CNI output.
This patch specifies version both for CNI conf and CNI output.

Signed-off-by: Alexey Perevalov <a.perevalov@samsung.com>

* kubelet: add CNI cache dir option and plumb through to CNI and kubenet

libcni 0.7.0 caches ADD operation results and allows the runtime to
retrieve these from the cache. In case the user wants a different
cache directory than the defaul, plumb that through like we do
for --cni-bin-dir and --cni-conf-dir.

* make update

* Fix malformed port in vsphere cloud provider test

The port name previously didn't matter on these tests, but is now
actively being checked in go1.12.8 and higher.

https://github.com/golang/go/commit/3226f2d492963d361af9dfc6714ef141ba606713

* Fix up failing boilerplate test

* update RSA keys to 2048 bits

* Fix TestUnreservePlugin

* call unreserve plugin before record event

* make update

* bump repo-infra, kazel, bazel, gazelle
hack/pin-dependency.sh k8s.io/repo-infra v0.0.1-alpha.1
To fix non-idempotent BUILD file generation

hack/pin-dependency.sh github.com/bazelbuild/bazel-gazelle v0.19.1
hack/pin-dependency.sh github.com/bazelbuild/buildtools v0.0.0-20190917191645-69366ca98f89
for go1.13 support

hack/lint-dependencies.sh
hack/update-vendor.sh

* make update

* Fix a double lock in test/utils

Signed-off-by: Ziheng Liu <lzhfromustc@gmail.com>

* update vendor dependencies: opencontainers/runc, k8s.io/gengo, libopenstorage/openstorage, docker/distribution
hack/pin-dependency.sh github.com/opencontainers/runc v1.0.0-rc2.0.20190611121236-6cc515888830
hack/pin-dependency.sh k8s.io/gengo v0.0.0-20190128074634-0689ccc1d7d6
hack/pin-dependency.sh github.com/libopenstorage/openstorage v1.0.0
hack/pin-dependency.sh github.com/docker/distribution v2.7.1+incompatible
hack/lint-dependencies.sh
hack/update-vendor.sh

* Fix cgroup hugetlb size prefix for kB: kubernetes#78495

* Bump dependency opencontainers/runc@v1.0.0-rc10
hack/pin-dependency.sh github.com/opencontainers/runc v1.0.0-rc10
hack/pin-dependency.sh github.com/cilium/ebpf v0.0.0-20191025125908-95b36a581eed
hack/pin-dependency.sh github.com/mrunalp/fileutils v0.0.0-20171103030105-7d4729fb3618
hack/pin-dependency.sh github.com/opencontainers/selinux v1.3.1-0.20190929122143-5215b1806f52
hack/pin-dependency.sh github.com/syndtr/gocapability v0.0.0-20180916011248-d98352740cb2
hack/pin-dependency.sh github.com/coreos/go-systemd v0.0.0-20190321100706-95778dfbb74e
hack/pin-dependency.sh github.com/godbus/dbus v0.0.0-20181101234600-2ff6f7ffd60f
hack/lint-dependencies.sh
hack/update-vendor.sh

* Rename cgroupsystemd.Manager to LegacyManager

* bump dependency k8s.io/gengo v0.0.0-20200205140755-e0e292d8aa12
hack/pin-dependency.sh k8s.io/gengo v0.0.0-20200205140755-e0e292d8aa12
hack/lint-dependencies.sh
hack/update-vendor.sh

* Add --include-test-files flag to verify-import-boss

* bump dependency checkpoint-restore/go-criu, elazarl/goproxy
hack/pin-dependency.sh github.com/checkpoint-restore/go-criu v0.0.0-20181120144056-17b0214f6c48
hack/pin-dependency.sh github.com/elazarl/goproxy v0.0.0-20180725130230-947c36da3153
hack/lint-dependencies.sh
hack/update-vendor.sh

* make update

* revert arktos version back to v0.2 in swagger.json

Co-authored-by: Jordan Liggitt <liggitt@google.com>
Co-authored-by: Patrick Ohly <patrick.ohly@intel.com>
Co-authored-by: Odin Ugedal <odin@ugedal.com>
Co-authored-by: Antoine Pelisse <apelisse@google.com>
Co-authored-by: Benjamin Elder <bentheelder@google.com>
Co-authored-by: Stephen Augustus <saugustus@vmware.com>
Co-authored-by: Sergiusz Urbaniak <sergiusz.urbaniak@gmail.com>
Co-authored-by: mattjmcnaughton <mattjmcnaughton@gmail.com>
Co-authored-by: Ryan Phillips <rphillips@redhat.com>
Co-authored-by: Dr. Stefan Schimanski <stefan.schimanski@gmail.com>
Co-authored-by: Tim Allclair <tallclair@google.com>
Co-authored-by: Alexey Perevalov <a.perevalov@samsung.com>
Co-authored-by: Dan Williams <dcbw@redhat.com>
Co-authored-by: Christoph Blecker <admin@toph.ca>
Co-authored-by: SataQiu <qiushida@beyondcent.com>
Co-authored-by: Alena Varkockova <varkockova.a@gmail.com>
Co-authored-by: danielqsj <qsj.daniel@gmail.com>
Co-authored-by: Ziheng Liu <lzhfromustc@gmail.com>
Co-authored-by: Davanum Srinivas <davanum@gmail.com>